Init
ist-dsi/scala-designate-client pull request #1
Opened 2020-04-23 21:35 UTC by afonsomatos

2020-04-23 23:24 UTC, Lasering requested changes

2020-04-23 23:24 UTC, Lasering commented on docker.sh
> +#!/bin/bash
Não vou conseguir arranjar um docker para fazer testes. Por isso este ficheiro não vai ser preciso.

2020-04-23 23:24 UTC, Lasering commented on project/Dependencies.scala
> +import sbt._
Este ficheiro não está a ser usado.

2020-04-23 23:24 UTC, Lasering commented on project/build.properties
> +sbt.version=1.2.7
Usa antes a versão 1.3.10 (a latest)

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/DesignateClient.scala
> +  val uri: Uri = keystoneClient.baseUri / "v2"
O servidor com a API do designate na maioria dos casos está num endereço diferente do servidor do keystone. Tens que receber a baseUri no construtor.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/DesignateClient.scala
> +class DesignateClient[F[_]: Sync](implicit keystoneClient: KeystoneClient[F], client: Client[F]) {
O Designate client não invoca métodos da API do Keystone por isso não faz sentido receberes um KeystoneClient. O que o designate cliente precisa é do authentication header (donde é que ele vem é responsabilidade do user da biblioteca). Ou seja, o construtor devia ter `val authToken: Header`.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/WithId.scala
> +import pt.tecnico.dsi.keystone.KeystoneClient
Este ficheiro não devia precisar do KeystoneClient. Quando muito do DesignateClient.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/WithId.scala
> +trait IdFetcher[T <: IdFetcher[T]] {
Quando formos generalizar isto para os vários módulos vamos ter que abstrair o `(Keystone|Designate)Client` para um type parameter.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/CRUDService.scala
> +  protected def unwrap(request: F[Request[F]]): F[WithId[T]] = client.expect[Map[String, WithId[T]]](request).map(_.apply(name))
Já que extraíste esta funcionalidade para o `BaseService`, devias estar a usá-la. Ou no mínimo estes metodos serem implementados em função dos metodos do `BaseService`.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/CRUDService.scala
> +  def disable(id: String)(implicit ev: T <:< Enabler[T]): F[Unit] = updateEnable(id, value = false)
Não encontrei na API do designate nada relativo a enable/disable. Acho que podes remover estes métodos.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/BaseService.scala
> +  protected def genericGet[T: Codec](name: String, id: String): F[WithId[T]] =
Não estás a usar isto em lado nenhum. Talvez querias usar dentro do CRUDService.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/BaseService.scala
> +  protected def genericUpdate[T: Codec, R: Codec](name: String, id: String, value: R): F[WithId[T]] =
Não estás a usar isto em lado nenhum. Talvez querias usar dentro do CRUDService.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/FloatingIPs.scala
> +
O nome `floatingIpId` é smurf notation, já estás dentro da classe FloatingIP.

Não precisas de dizer explicitamente o tipo ao expect. Ele vai conseguir inferir pelo tipo de retorno do metodo.

Devias usar string interpolation fica mais fácil de ler:
```scala
GET(uri / s"$region:$floatingIpId", authToken)
```

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/FloatingIPs.scala
> +  def list: Stream[F, FloatingIP] = genericList[FloatingIP]("floatingips", uri)
O list devolve `WithId[FloatingIP]`

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/FloatingIP.scala
> +  address: String,
address devia ter o tipo [InetAddress](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/net/InetAddress.html)

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/FloatingIP.scala
> +  ttl: String,
ttl devia ter o tipo [FiniteDuration](https://www.scala-lang.org/api/current/scala/concurrent/duration/FiniteDuration.html)

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/FloatingIP.scala
> +  ptrdname: String,
ptrdname devia ter um tipo que represente um domain name. De momento não estou a encontrar o tipo certo.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/FloatingIPs.scala
> +import pt.tecnico.dsi.designate.models.{FloatingIP, Quota}
Quota não está a ser usado.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Quotas.scala
> +
Não precisas de dizer o tipo ao expect. Ele vai conseguir inferir.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Quotas.scala
> +    client.expect[Quota](PATCH(uri / projectId, authToken))
Não chegas a usar o parâmetro `quota` devia ser `PATCH(quota, uri / projectId, authToken)`.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Limits.scala
> +object Limits {
Isto devia ser implementado directamente na class DesignateClient.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Recordsets.scala
> +  def list[F[_]: Sync: Client](baseUri: Uri, authToken: Header): Stream[F, WithId[Recordset]]
Igualmente ao limits, isto devia estar implementado directamente no DesignateCliente.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Recordsets.scala
> +trait ListService[F[_]] { this: BaseService[F] =>
Não percebo o propósito desta classe.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/Recordset.scala
> +  name: String,
Como no FloatingIP name devia ter um tipo que represente um domain name. De momento não estou a encontrar o tipo certo.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/Recordset.scala
> +  TTL: String,
Porquê maiúsculas? Devia ser uma FiniteDuration.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/Recordset.scala
> +  description: String,
O description não devia ser Option[String]?

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/Recordset.scala
> +  records: Seq[String]
records devia ser `List[InetAddress]`.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/Recordset.scala
> +)
Podias ter um método que devolve a zone. Como a classe User no Keystone tem um método que devolve o domain a que o user pertence.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/ZoneTransferAccepts.scala
> +  override val uri: Uri = baseUri
Devia ser:
```scala
override val uri: Uri = baseUri / "transfer_accepts"
```

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Zones.scala
> +  val tasks: Uri = uri / "tasks"
Devia ser:
```scala 
object tasks {
  val uri: Uri = self.uri / "tasks"
  val transferRequests = new ZoneTransferRequests[F](uri, authToken)
  val transferAccepts = new ZoneTransferAccepts[F](uri, authToken)
}
```
Precisas de uma self type annotation na classe Zones para teres o self.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/ZoneTransferRequests.scala
> +  override val uri: Uri = baseUri
Devia ser:
```scala
override val uri: Uri = baseUri / "transfer_requests"
```

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/ZoneTransferRequests.scala
> +  val crud: CRUDService[F, ZoneTransferRequest]
Devia ser privado. É indicativo que ou a classe CRUDService não é flexivel o suficiente, ou então que não devias precisar disto, e implementar o delete,list,update usando os metodos do BaseService (como fizeste para os ZoneTransferAccepts).

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/ZoneTransferRequests.scala
> +    = client.expect[WithId[ZoneTransferRequest]](POST(uri, authToken))
Isto parece que não foi implementado.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/ZoneTransferRequests.scala
> +  def list: Stream[F, WithId[ZoneTransferRequest]] = crud.list()
Devias fazer overload ao metodo list para suportar filtrar a list por o status.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/ZoneTransferRequest.scala
> +  targetProjectId: String,
Parece-me que o campo `targetProjectId` devia ser `Option[String]`.

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/ZoneTransferAccepts.scala
> +      Map("key" -> key, "zone_transfer_request_id" -> zoneTransferRequestId),
Devia ser `Map(...).asJson`, precisas de `import io.circe.syntax._`

2020-04-23 23:24 UTC, Lasering commented on src/test/scala/pt/tecnico/dsi/designate/Base.scala
> +  def designate: IO[DesignateClient[IO]] = scopedClient.map(s => {
Isto devia estar logo no Utils

2020-04-23 23:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/Zone.scala
> +case class Zone(
Não gosto destes Options todos.

2020-05-03 20:38 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/CRUDService.scala
> +  protected def unwrap(request: F[Request[F]]): F[WithId[T]] = client.expect[Map[String, WithId[T]]](request).map(_.apply(name))
Pelo que vi o `unwrap` na API não se aplica tal como se aplicava no Keystone. Pode ser necessário no futuro, mas até agora não vi aplicações.

2020-05-03 20:49 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/FloatingIPs.scala
> +  def list: Stream[F, FloatingIP] = genericList[FloatingIP]("floatingips", uri)
Também dei fix ao `get` e ao `set`, que também deviam retornar um `WithId`.

2020-05-03 20:53 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/models/FloatingIP.scala
> +  ptrdname: String,
Uri? InetAddress?

2020-05-03 21:12 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/models/Recordset.scala
> +  TTL: String,
Não existem Decoders do FiniteDuration e do InetAddress, por isso ele falha.

2020-05-03 21:15 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/Recordsets.scala
> +trait ListService[F[_]] { this: BaseService[F] =>
Ele não me deixa usar o `.list` no Recordsets se não tiver a usar este trait.

2020-05-03 21:21 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/models/Recordset.scala
> +  description: String,
O description e outros talvez deveriam ser `Option[String]`. Tenho que discutir contigo uma divisão dos tipos dependendo de ser update/create/delete. Os options estragam um bocado a simplicidade da api.

2020-05-03 21:33 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/ZoneTransferRequests.scala
> +  val crud: CRUDService[F, ZoneTransferRequest]
Sim, parece que defacto um CRUD assenta bem aqui, tornei-a uma subclasse.

2020-05-03 21:45 UTC, afonsomatos commented on src/test/scala/pt/tecnico/dsi/designate/Base.scala
> +  def designate: IO[DesignateClient[IO]] = scopedClient.map(s => {
Eu meti isto aqui só para testar. Dou refactor quando soubermos exatamente como vamos testar.

2020-05-03 21:46 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/models/Zone.scala
> +case class Zone(
O que me leva a uma conversa que temos de ter de como lidar com os tipos altamente assimétricos nas operações cruds.

2020-05-04 13:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/FloatingIP.scala
> +  ptrdname: String,
URI é demasiado, tem protocolo, domain name, porta, e path. InetAddress representa um IP.
Seria algo tipo isto https://guava.dev/releases/19.0/api/docs/com/google/common/net/InternetDomainName.html mas não sei se vale a pela ir buscar esta dependência só para isto.

2020-05-04 13:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/Recordset.scala
> +  records: Seq[String]
Acho que te escapou este.

2020-05-04 13:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/FloatingIPs.scala
> +    client.expect(PATCH(floatingIp, uri / (region + ":" + floatingIpId), authToken))
Aqui também podes fazer string interpolation.

2020-05-04 13:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/FloatingIPs.scala
> +    client.expect(PATCH(Map("ptrdname" -> None), uri / (region + ":" + floatingIP)))
E aqui também.

2020-05-04 13:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/DesignateClient.scala
> +  def recordsets: Stream[F, WithId[Recordset]] = new BaseService[F](authToken) with ListService[F] {
Isto não está a fazer muito sentido. Criaste a class ListService simplesmente para implementar o método list que depois é logo chamado. Podes logo chamar o método genericList.

2020-05-06 17:46 UTC, merged