Add generic type fields to CRUD
ist-dsi/scala-designate-client pull request #2
Opened 2020-05-25 09:53 UTC by afonsomatos

2020-06-03 12:30 UTC, Lasering requested changes

2020-06-03 12:30 UTC, Lasering commented on build.sbt
> +testOptions in Test += Tests.Argument(TestFrameworks.ScalaTest, "-oDF")
-F sem um span scale factor faz alguma coisa?

Adiciona aos comentários o que é que o -F faz.

2020-06-03 12:30 UTC, Lasering commented on openstack-openrc.sh
> +export OS_PASSWORD="oJiCK3dhiZ6TilT64Pl9B72tfjtNHpla"
Fazer commit de passwords é sempre má prática. Agora qualquer pessoa pode entrar dentro da máquina e chafurdar. Vou ter que criar uma máquina nova.

2020-06-03 12:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/models/Zone.scala
> +  implicit val codec: Codec[Zone] = deriveCodec[Zone](renaming.snakeCase, false, None)
Descobri que estamos a fazer os derived* de forma complicada. Pode ser simplesmente:
`deriveCodec(renaming.snakeCase)`

A mesma coisa para os outros neste projecto.

2020-06-03 12:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/AsymmetricCRUDService.scala
> +abstract class AsymmetricCRUDService[F[_]: Sync: Client, T: Codec](baseUri: Uri, val name: String, authToken: Header)
Muda o nome do T para Model, do U para Update, e do C para Create.

2020-06-03 12:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/BaseService.scala
>    protected def unwrap[T: Codec](request: F[Request[F]], name: String): F[WithId[T]] =
O unwrap apenas precisa de um Decoder.

2020-06-03 12:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Zones.scala
> +  override def get(id: String): F[WithId[Zone]] =
Este método não vem já do AsymmetricCRUDService?

2020-06-03 12:30 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Zones.scala
> +  def update(id: String, value: U): F[WithId[Zone]] =
Este método não vem já do AsymmetricCRUDService?

2020-06-04 10:23 UTC, afonsomatos commented on build.sbt
> +testOptions in Test += Tests.Argument(TestFrameworks.ScalaTest, "-oDF")
O `-F` mostra o stack trace completo sempre que dá um erro.

2020-06-04 10:37 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/BaseService.scala
>    protected def unwrap[T: Codec](request: F[Request[F]], name: String): F[WithId[T]] =
O unwrap na verdade precisa de um decoder de `Map[String, WithId[T]]`

2020-06-04 11:03 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/BaseService.scala
>    protected def unwrap[T: Codec](request: F[Request[F]], name: String): F[WithId[T]] =
O problema é que porcausa de ser um `WithId`, eu preciso de um decoder de `WithId[T]`. Se eu colocar `T: Codec` ele consegue ir buscar esse decoder implicitamente.

2020-06-04 11:37 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/BaseService.scala
>    protected def unwrap[T: Codec](request: F[Request[F]], name: String): F[WithId[T]] =
Também deveria conseguir na mesma. Mas se não está a conseguir, temos que mudar ligeiramente o codec do WithId para também termos o Encoder e o Decoder implicitos.

2020-06-04 17:54 UTC, Lasering requested changes

2020-06-04 17:54 UTC, Lasering commented on build.sbt
> +testOptions in Test += Tests.Argument(TestFrameworks.ScalaTest, "-oDF")
Adiciona ao comentário para que é que o F serve.

2020-06-07 18:57 UTC, Lasering approved these changes

2020-06-07 18:58 UTC, merged