More tests
ist-dsi/scala-designate-client pull request #3
Opened 2020-06-10 19:46 UTC by afonsomatos

2020-06-16 14:43 UTC, Lasering requested changes

2020-06-16 14:43 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/AsymmetricCRUDService.scala
> +  def update(id: String, value: Update)(implicit d: Codec[Update]): F[WithId[Model]] = genericUpdate[Model, Update](id, value)
Aqui não basta ter um `Encoder[Update]`?
Não percebo porque é que tiveste que criar este método, bastava teres o metodo `update` no baseService.

2020-06-16 14:43 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/BaseService.scala
> +  protected def genericUpdate[T: Codec, R: Codec](id: String, value: R): F[WithId[T]] =
Todos os outros metodos desta classe não têm generic no nome, porque é que foi preciso ter nesta?

2020-06-16 14:43 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/BaseService.scala
>    protected def get[T: Codec](id: String): F[WithId[T]] = unwrap(GET(uri / id, authToken))
Aqui devia ser apenas `[T: Decoder]`, e o mesmo no `unwrap`.

2020-06-16 14:43 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/AsymmetricCRUDService.scala
>    protected def createHandleConflict(value: Create)(onConflict: Response[F] => F[WithId[Model]])
No `create` devia ser apenas `Encoder[Create]` em vez do Codec

2020-06-16 14:43 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Recordsets.scala
> +  override def update(id: String, value: RecordsetUpdate)(implicit d: Codec[Update]): F[WithId[Recordset]] =
Porque tiveste que implementar o metodo update aqui? O que vem do AsymmetricCRUDService já parece ser o certo?

2020-06-16 14:43 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/designate/services/Recordsets.scala
> +  override def create(value: Create)(implicit codec: Codec[Create]): F[WithId[Recordset]] = createHandleConflict(value) { _ =>
Devia ser `Encoder[RecordsetCreate]`.

2020-06-16 14:43 UTC, Lasering commented on src/test/scala/pt/tecnico/dsi/designate/QuotasSpec.scala
Aqui há imenso código repetido, mas vai ser mais fácil arranjar isso mais para o fim.

2020-06-16 14:43 UTC, Lasering commented on src/test/scala/pt/tecnico/dsi/designate/ZonesSpec.scala
> +            actual.model.email == dummyZoneCreate.email &&
Não precisas dos `.model`

2020-06-16 14:43 UTC, Lasering commented on src/test/scala/pt/tecnico/dsi/designate/ZonesSpec.scala
> +        isIdempotent <- client.zones.get(expected.id).idempotently(_.model shouldEqual expected.model)
A não ser que os links venham diferentes aqui podes comparar directamente o WithId visto que os ids são iguais.

2020-06-16 14:43 UTC, Lasering commented on src/test/scala/pt/tecnico/dsi/designate/ZonesSpec.scala
> +          val equalDesc = {
```scala
val equalDesc = dummyZoneUpdate.description.zip(actual.model.description).forall{ case (expected, actual) => expected == actual }
```
ou se quiseres ainda mais pequeno
```scala
val equalDesc = dummyZoneUpdate.description.zip(actual.model.description).forall(t => t._1 == t._2)
```

2020-06-16 14:48 UTC, Lasering requested changes
Mudei um comentario

2020-06-16 20:23 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/Recordsets.scala
> +  override def update(id: String, value: RecordsetUpdate)(implicit d: Codec[Update]): F[WithId[Recordset]] =
Porque este usa o PUT e não o PATCH.

2020-06-16 20:36 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/AsymmetricCRUDService.scala
> +  def update(id: String, value: Update)(implicit d: Codec[Update]): F[WithId[Model]] = genericUpdate[Model, Update](id, value)
O método update do BaseService não tem as restrições do tipo (Create, Update, Model). Tive que criar essa função para invocar a do BaseService com os tipos certos.

2020-06-16 20:39 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/designate/services/AsymmetricCRUDService.scala
> +  def update(id: String, value: Update)(implicit d: Codec[Update]): F[WithId[Model]] = genericUpdate[Model, Update](id, value)
Quando troco de Codecs para Encoders/Decoders ele reclamava que não encontra um EntityDecoder[F, A], consegues ver do que se trata?

2020-06-17 10:02 UTC, Lasering approved these changes

2020-06-18 13:32 UTC, merged